version: '3.8'
# este es un ejemplo
# este es otro ejemplo
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env.development     
    environment:
      - DB_HOST=host.docker.internal   
    ports:
      - "3002:3002"
    volumes:
      - ./:/app
      - /app/node_modules
    command: ["npm", "run", "start"]
    restart: on-failure

volumes:
  db_data: